---
- name: Create php-apache deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          sidecar.speedscale.com/inject: "true"
          sidecar.speedscale.com/capture-mode: "proxy"
        namespace: "{{ namespace }}"
        name: php-apache
      spec:
        selector:
          matchLabels:
            run: php-apache
        replicas: 3
        template:
          metadata:
            labels:
              run: php-apache
          spec:
            containers:
            - name: php-apache
              image: k8s.gcr.io/hpa-example
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 80
              resources:
                limits:
                  cpu: 500m
                requests:
                  cpu: 200m

- name: Create php-apache service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: php-apache
        namespace: "{{ namespace }}"
        labels:
          run: php-apache
      spec:
        ports:
        - port: 80
        selector:
          run: php-apache

- name: Create php-apache deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        namespace: "{{ namespace }}"
        name: infinite-calls
        labels:
          app: infinite-calls
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: infinite-calls
        template:
          metadata:
            name: infinite-calls
            labels:
              app: infinite-calls
          spec:
            containers:
            - name: infinite-calls
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - "while true; do wget -q -O- http://php-apache; sleep 3.5; done"

- name: Wait untill logs get sent
  command: sleep 100

- name: Delete inifite calls deployment
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        namespace: "{{ namespace }}"
        name: infinite-calls
        labels:
          app: infinite-calls
